"""
05. Final Report Generator
===========================
A markdown report that references the generated PNGs already stored in
outputs/figures/.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from src.data_utils import FIGURES_DIR, REPORTS_DIR

REPORT_TEMPLATE = """# Olist E-commerce: A Data-Driven Diagnosis for Growth

## Summary
This analysis examines the already-joined Olist export files and tracks the
customer journey from order to review across {n_orders_placeholder} orders.

Two consistent conclusions emerge:
1. Customer dissatisfaction tracks delivery delay.
2. The business is overwhelmingly a single-purchase acquisition engine.

## Finding 1: Delivery Delay Drives Dissatisfaction
![Shipping time vs review score](../outputs/figures/box_shipping_time_by_review_score.png)

## Finding 2: Product Category Performance Map
![Category performance bubble plot](../outputs/figures/category_performance_bubble_plot.png)

## Finding 3: The Single-Purchase Problem
![Customer segment distribution](../outputs/figures/customer_segments_distribution.png)
![K-Means vs manual segments](../outputs/figures/heatmap_comparison_segments.png)

## Finding 4: Predictive Modeling
![Prophet forecast vs actual](../outputs/figures/prophet_forecast_vs_actual.png)
![Random Forest ROC curve](../outputs/figures/roc_curve_random_forest.png)

---

*Generated by scripts/05_final_report.py.*
"""


def main() -> None:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORTS_DIR / "final_report.md"

    missing = [
        "box_shipping_time_by_review_score.png",
        "category_performance_bubble_plot.png",
        "customer_segments_distribution.png",
        "heatmap_comparison_segments.png",
        "prophet_forecast_vs_actual.png",
        "roc_curve_random_forest.png",
    ]
    missing = [f for f in missing if not (FIGURES_DIR / f).exists()]
    if missing:
        print("Warning: these figure files are missing:")
        for f in missing:
            print(f"  - {f}")

    report_path.write_text(REPORT_TEMPLATE.format(n_orders_placeholder="~98,000"))
    print(f"Report written to {report_path}")


if __name__ == "__main__":
    main()
